baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'cPanel Project'
theme = "PaperMod"

[menu]
[[menu.main]]
  identifier = 'Breakfast'
  name = 'Breakfast'
  url = '/Breakfast/'
  weight = 10
[[menu.main]]
  name = 'Lunch'
  url = '/Lunch/'
  weight = 20
  [[menu.main]]
  name = 'Dinner'
  url = '/Dinner/'
  weight = 30
